### PR TITLE
WIP Openstack cloud provider

### PR DESCRIPTION
**Pull request by tghartland**
Making PR here for initial comments.

### CODE REVIEW

**Comment by tghartland** [comment]
**Testing instructions**

- Build (and push to container registry of your choice)
```
$ export BUILD_TAGS=openstack
$ make build-binary
$ docker build -t thartland/os-autoscaler .
$ docker push thartland/os-autoscaler
```

- Service account (otherwise: "Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "nodes" in API group "" at the cluster scope"). It also needs access to a bunch of other things (endpoints, services, pods, statefulsets, replicasets....) so I've left as resources: "*" for now. Can optimise to what exactly needs create/delete and what only needs get/list later.

```
$ cat svcaccount-autoscaler.yaml 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: os-autoscaler-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: os-autoscaler-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: os-autoscaler-role
subjects:
- kind: ServiceAccount
  name: os-autoscaler-account
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-autoscaler-account
  namespace: kube-system
```

- Get  kube_openstack_config from master node

```
$ scp fedora@scaler-02-d5hgjhjra4wc-master-0:/etc/kubernetes/kube_openstack_config .
$ kubectl -n kube-system create secret generic autoscaler-os-secrets --from-file=kube_openstack_config
```

- Deployment for autoscaler

```
$ cat autoscaler.yaml 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: os-autoscaler
  namespace: kube-system
  labels:
    app: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      namespace: kube-system
      labels:
        app: autoscaler
    spec:
      serviceAccountName: os-autoscaler-account
      containers:
        - name: os-autoscaler
          image: thartland/os-autoscaler
          command:
            - ./cluster-autoscaler
            - --alsologtostderr
            - --cluster-name=scaler-02 # <------------------------------ CHANGE THIS
            - --cloud-config=/config/kube_openstack_config
            - --scale-down-unneeded-time=30s
            - --scale-down-delay-after-add=30s
            - --scale-down-delay-after-failure=1m
            - --nodes=1:10:DefaultNodeGroup
          volumeMounts:
            - name: kube-openstack-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: kube-openstack-config
          secret:
            secretName: autoscaler-os-secrets
```
- Run
```
$ kubectl create -f svcaccount-autoscaler.yaml -f autoscaler.yaml
$ kubectl -n kube-system logs --follow $(kubectl -n kube-system get pods -o name | grep autoscaler)
```

**Comment by openstacker** [comment]
@tghartland Thanks for the great work. The deployment yaml looks good and I'm keen to test it. I think it would be great if you put it into one file as a part of this PR so that others can be benefited for testing. Thanks.

**Comment by openstacker** [comment]
Question: How the '- --cluster-name' is used in CA? As you may know, in Magnum, the kubernetes cluster name could be duplicated, will it be a problem at this case? Thanks.

**Comment by openstacker** [comment]
Question: Do we need the '- --cloud-provider=openstack' option?

**Comment by tghartland** [comment]
@openstacker thanks for the feedback.
> As you may know, in Magnum, the kubernetes cluster name could be duplicated, will it be a problem at this case?

I actually didn't know this, I'm surprised to learn that it works like that and I don't really see how it would be useful. If there is some reason to do this, then the cluster ID can be given to --cluster-name and it works as expected.

> Do we need the '- --cloud-provider=openstack' option?

I have been building my container image with `BUILD_TAGS=openstack` so openstack is the default (and only) cloud provider. If you build a generic autoscaler then it will require ` --cloud-provider=openstack`.

I'll add an examples directory with the cloud provider like some of the others have, good idea. A README.md with some documentation like the cluster name/ID being interchangeable might be useful as well.

**Comment by brtkwr** [comment]
Nice work @tghartland! AFAIK, `--cloud-provider=openstack` has been deprecated in favour of `--cloud-provider=external`, with control loop for cloud providers running separately: https://github.com/kubernetes/cloud-provider-openstack

**Comment by tghartland** [comment]
@brtknr maybe I misunderstood the question from @openstacker. `--cloud-provider=external` is the option for the kubelet, I was referring to the `--cloud-provider` argument to the autoscaler itself.

At CERN we are not yet running an external cloud-controller-manager so there is no Node Controller, which is why I have had to clean up the nodes which were removed by scaling down from the kubernetes nodes list myself, here https://github.com/cernops/autoscaler/pull/3/files#diff-e5c00e6f151663a8bd7e5cd43dddeb66R35. I don't think this would interfere too much in a cluster with the proper node controller from the openstack cloud-controller-manager, but I'd like to find the best way to deal with both situations.

**Comment by openstacker** [comment]
> Nice work @tghartland! AFAIK, `--cloud-provider=openstack` has been deprecated in favour of `--cloud-provider=external`, with control loop for cloud providers running separately: https://github.com/kubernetes/cloud-provider-openstack

I"m not talking about the --cloud-provider of controller manager, I'm talking about the config option for autoscaler.

@tghartland We had used cluster ID for --cluster-name for other CCM, I'm just trying to figure out how the Autoscaler uses it to avoid any surprise in the future.

**Comment by tghartland** [comment]
The cluster name is only used for interacting with the magnum API, mostly `Get`s and one `Update`.
```go
cluster, err := clusters.Get(osm.clusterClient, osm.clusterName).Extract()
```
For this type of call the name and ID are interchangeable. There shouldn't be anything else that would catch you out.

**Comment by openstacker** [comment]
> The cluster name is only used for interacting with the magnum API, mostly `Get`s and one `Update`.
> 
> ```go
> cluster, err := clusters.Get(osm.clusterClient, osm.clusterName).Extract()
> ```
> 
> For this type of call the name and ID are interchangeable. There shouldn't be anything else that would catch you out.

Great, thanks for the clarification.

**Comment by strigazi** [comment]
Can these 35 commits be reorganized a bit? I don't think this will be accepted upstream like this. For examples "Almost working heat delete" can surely be squashed or at least renamed. I think one commit for dependencies, one for feature implementation, one for tests and one for docs should be enough, (some refactoring changes can also stand on their own)

**Comment by tghartland** [comment]
@strigazi I'm making things even messier on my upstreaming branch now https://github.com/tghartland/autoscaler/commits/openstack-provider-upstream.

I'll try to organise things as best I can. It might be best to move into a new branch and just copy over the final versions of files, committing each group separately (code/docs/tests).

**Comment by strigazi** [comment]
New branch is the best option.
Keep this for reference and we can polish it.

What we will also need in the docs is, explaining that this magnum specific at the moment.

I'm testing this branch, shall I focus on another one?

**Comment by tghartland** [comment]
The branch https://github.com/tghartland/autoscaler/commits/openstack-provider-upstream is now the clean and up to date one.

**Comment by tghartland** [comment]
For the docs, what's the correct way to say that only magnum/heat clusters are supported? Is it "using heat" or "with the heat driver" or ....?

**Comment by openstacker** [comment]
Currently, my testing is based on https://github.com/tghartland/autoscaler/commits/openstack-provider-upstream but please please let's keep one repo to make sure everyone on the same page. So far, I can start the NPD + draino + CA, but CA is failing with below error:

<pre>
F0201 01:44:14.711203       1 openstack_cloud_provider.go:116] Failed to create openstack manager: could not store stack name on manager: could not get stack from heat: Resource not found
goroutine 44 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.stacks(0xc42046bf00, 0xc420483c00, 0xbc, 0x1ee)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:828 +0xcf
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.(*loggingT).output(0x3d341e0, 0xc400000003, 0xc420b44840, 0x3c953ed, 0x1b, 0x74, 0x0)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:779 +0x30f
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.(*loggingT).printf(0x3d341e0, 0x3, 0x27d2d8a, 0x26, 0xc4207a2da0, 0x1, 0x1)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:678 +0x14b
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.Fatalf(0x27d2d8a, 0x26, 0xc4207a2da0, 0x1, 0x1)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:1207 +0x67
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/openstack.BuildOpenstack(0xa, 0x3fe0000000000000, 0x6fc23ac00, 0x1176592e000, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, 0x3d52b88, ...)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/openstack/openstack_cloud_provider.go:116 +0x15b
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder.buildCloudProvider(0xa, 0x3fe0000000000000, 0x6fc23ac00, 0x1176592e000, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, 0x3d52b88, ...)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder/builder_all.go:62 +0x508
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder.NewCloudProvider(0xa, 0x3fe0000000000000, 0x6fc23ac00, 0x1176592e000, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, 0x3d52b88, ...)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go:45 +0x1d5
k8s.io/autoscaler/cluster-autoscaler/core.initializeDefaultOptions(0xc4207a38f8, 0x29cfd40, 0xc4202c8400)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:92 +0x2f4
k8s.io/autoscaler/cluster-autoscaler/core.NewAutoscaler(0xa, 0x3fe0000000000000, 0x6fc23ac00, 0x1176592e000, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, 0x3d52b88, ...)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:61 +0x43
main.buildAutoscaler(0x699468, 0xc4200ba000, 0x29d5140, 0xc420044018)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/main.go:293 +0x340
main.run(0xc420096e60)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/main.go:299 +0x2e
main.main.func2(0x29d5100, 0xc42034aec0)
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/main.go:390 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /home/feilong/MyWorkspace/workspace_k8s/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:170 +0xee

</pre>

**Comment by openstacker** [comment]
All my work is using https://review.openstack.org/#/c/631378/ to track.
@tghartland 

BTW, given there is no node group support in Magnum now. So what's the current test scenario? for example, if draino just drained a node, how can I do the configure to make CA can automatically replace that node? Thanks.

**Comment by tghartland** [comment]
@openstacker The first thing that comes to mind is that in gophercloud, requests for the stack take both a stack name and stack ID. The cluster only has the stack ID, but for me it has been possible to `Get` the stack with only the ID, and this gives the name to use from then on.

I have just added some logging to the two functions that get the stack name and ID.
https://github.com/tghartland/autoscaler/blob/openstack-provider-upstream/cluster-autoscaler/cloudprovider/openstack/openstack_manager_heat.go#L221-L239

Could you test and and check that the stack ID is the same as you see with `openstack stack list`?
This is what I see

```
I0201 10:49:35.752920       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/cluster-autoscaler...                                                                                                                                                     
I0201 10:49:56.804520       1 leaderelection.go:214] successfully acquired lease kube-system/cluster-autoscaler                                                                                                                                                                
I0201 10:49:57.473664       1 openstack_manager_heat.go:222] Getting cluster "scaler-01"                                                                                                                                                                                       
I0201 10:49:58.479434       1 openstack_manager_heat.go:227] Cluster stack ID: "3562932c-eb05-4b01-8e93-b8f055abc1cf"                                                                                                                                                          
I0201 10:49:58.479458       1 openstack_manager_heat.go:232] Getting stack name for stack ID "3562932c-eb05-4b01-8e93-b8f055abc1cf"                                                                                                                                            
I0201 10:49:58.618350       1 openstack_manager_heat.go:237] For stack ID "3562932c-eb05-4b01-8e93-b8f055abc1cf" name is "scaler-01-tho66egtgobr"
```
```
$ openstack stack list
+--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+                                                                                                                                  
| ID                                   | Stack Name                         | Stack Status    | Creation Time        | Updated Time         |                                                                                                                                  
+--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+                                                                                                                                  
| 3562932c-eb05-4b01-8e93-b8f055abc1cf | scaler-01-tho66egtgobr             | UPDATE_COMPLETE | 2019-01-14T09:14:49Z | 2019-01-31T16:00:44Z |
+--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+
```

If I don't save the stack name and use an empty string I do get errors in other stack operations, so if the stack ID is correct you could try hardcoding in the stack name in `GetStackName` (second parameter in stacks.Get) to rule out this as a possibility. Otherwise it might be some sort of permissions issue.

Also, I have copied some more restrictive RBAC roles from one of the other cloud provider examples, you can update your patch with [these](https://github.com/tghartland/autoscaler/blob/openstack-provider-upstream/cluster-autoscaler/cloudprovider/openstack/examples/os-autoscaler-svcaccount.yaml).

**Comment by tghartland** [comment]
And for your follow up question, if the drained pods go into an unschedulable state then the CA will scale up if possible and the pods will be scheduled on the new node. After the drained node has been empty for a set amount of time it will be scaled down. Does that fit what you mean by "replace" the node?

**Comment by openstacker** [comment]
> @openstacker The first thing that comes to mind is that in gophercloud, requests for the stack take both a stack name and stack ID. The cluster only has the stack ID, but for me it has been possible to `Get` the stack with only the ID, and this gives the name to use from then on.
> 
> I have just added some logging to the two functions that get the stack name and ID.
> https://github.com/tghartland/autoscaler/blob/openstack-provider-upstream/cluster-autoscaler/cloudprovider/openstack/openstack_manager_heat.go#L221-L239
> 
> Could you test and and check that the stack ID is the same as you see with `openstack stack list`?
> This is what I see
> 
> ```
> I0201 10:49:35.752920       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/cluster-autoscaler...                                                                                                                                                     
> I0201 10:49:56.804520       1 leaderelection.go:214] successfully acquired lease kube-system/cluster-autoscaler                                                                                                                                                                
> I0201 10:49:57.473664       1 openstack_manager_heat.go:222] Getting cluster "scaler-01"                                                                                                                                                                                       
> I0201 10:49:58.479434       1 openstack_manager_heat.go:227] Cluster stack ID: "3562932c-eb05-4b01-8e93-b8f055abc1cf"                                                                                                                                                          
> I0201 10:49:58.479458       1 openstack_manager_heat.go:232] Getting stack name for stack ID "3562932c-eb05-4b01-8e93-b8f055abc1cf"                                                                                                                                            
> I0201 10:49:58.618350       1 openstack_manager_heat.go:237] For stack ID "3562932c-eb05-4b01-8e93-b8f055abc1cf" name is "scaler-01-tho66egtgobr"
> ```
> ```
> $ openstack stack list
> +--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+                                                                                                                                  
> | ID                                   | Stack Name                         | Stack Status    | Creation Time        | Updated Time         |                                                                                                                                  
> +--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+                                                                                                                                  
> | 3562932c-eb05-4b01-8e93-b8f055abc1cf | scaler-01-tho66egtgobr             | UPDATE_COMPLETE | 2019-01-14T09:14:49Z | 2019-01-31T16:00:44Z |
> +--------------------------------------+------------------------------------+-----------------+----------------------+----------------------+
> ```
> If I don't save the stack name and use an empty string I do get errors in other stack operations, so if the stack ID is correct you could try hardcoding in the stack name in `GetStackName` (second parameter in stacks.Get) to rule out this as a possibility. Otherwise it might be some sort of permissions issue.
> 
> Also, I have copied some more restrictive RBAC roles from one of the other cloud provider examples, you can update your patch with [these](https://github.com/tghartland/autoscaler/blob/openstack-provider-upstream/cluster-autoscaler/cloudprovider/openstack/examples/os-autoscaler-svcaccount.yaml).

Thanks for the quick response. Yep, after hardcode the stack name, the pod runs OK so far. I will dig this issue continually.

**Comment by openstacker** [comment]
> And for your follow up question, if the drained pods go into an unschedulable state then the CA will scale up if possible and the pods will be scheduled on the new node. After the drained node has been empty for a set amount of time it will be scaled down. Does that fit what you mean by "replace" the node?

Yep, that's basically the case I'm working on. In Magnum, we're working on a feature named 'auto healing/repairing', and this PR is one of the important parts. I will keep testing this and post feedback here. Thank you for the nice work. Cheers.

**Comment by tghartland** [comment]
@openstacker listing all stacks and finding the one with the matching ID to get the stack name should solve this. https://github.com/tghartland/autoscaler/commit/696914f536dd7421359df6093bd5447aab20bbed.

It's weird that what I had before worked for me and not for you though. Thanks for your testing.

**Pull request closed without merging**
